[app]
PageSize = 10
JwtSecret = "233"

ImagePrefixUrl = "http://127.0.0.1:8000"
ImageSavePath = "static/upload/images/"
# MB
ImageMaxSize = 5
ImageAllowTypes = "image/jpeg,image/jpg,image/jpeg"

LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = ".log"

[server]
#debug or release
RunMode = "debug"
HttpPort = 8000
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = "mysql"
User = "root"
Password = "123456"
Host = "127.0.0.1:3306"
Name = "go_blog"
TablePrefix = ""
MaxIdleConns = 10
MaxOpenConns = 100

[redis]
  [redis.master]
      Host = "127.0.0.1"
      Port = "6379"
      Password = "123456"
      MaxActive = 30
  [redis.slave]
      Host = "127.0.0.2"
      Port = "6380"
      Password = "654321"
      MaxActive = 30